# simulation parameters
minNumTissues: 3
maxNumTissues: 30
NtissueSamples: 5
Ngenes: 50
Nsamples: 200

# task-specific parameters
noise_sigma: 0.1
rarectFrac: 0.05
ctsMissingFromAtlas: 5

# solver parameters
C: 1.0
epsilon: 0.1

# save
folder: rarect
